- name: "SQS Queue"
  vars:
    resource: "arn:aws:sqs:{{ region }}:{{ aws.account }}:{{ item.name }}"
  sqs_queue:
    name: "{{ item.name }}"
    region: "{{ region }}"
    default_visibility_timeout: "{{ item.VisibilityTimeout | default(sqs.default.VisibilityTimeout) }}"
    receive_message_wait_time: "{{ item.ReceiveMessageWaitTimeSeconds | default(sqs.default.ReceiveMessageWaitTimeSeconds) }}"
    delivery_delay: "{{ item.DelaySeconds | default(sqs.default.DelaySeconds) }}" 
    policy:
      Version: "2008-10-17"
      Id: "__default_policy_ID"
      Statement: "{{ item.PolicyStatement | default(sqs.default.PolicyStatement) | combine( { 'Resource': resource} ) }}"
    queue_type: "{{ item.type | default('standard') }}"
    content_based_deduplication: "{{ item.deduplication | default(omit) }}"
  loop_control:
    label: "{{ item.name }}"
  loop: "{{ sqs.queues }}"

- name: "Create S3/SQS Triggers"
  include_tasks: "s3.yml"
  when: triggers is defined and triggers.buckets is defined and triggers.buckets | length > 0
